baseURL: "https://omers.github.io/"
title: Omers Blog
paginate: 15
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


languages:
  he:
    languagedirection: rtl
    title: הבלוג של עומר
    weight: 2
  en:
    params:
      linkedin: https://linkedin.com/whoever
    title: Omers Blog
    weight: 1


googleAnalytics: G-21XGG2919L
outputs:
    home:
        - HTML
        - RSS
        - JSON

minify:
  disableXML: false
  minifyOutput: true


params:
  env: production
  title: Omers Blog
  description: "ExampleSite description"
  keywords: [Blog, Portfolio]
  author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: false # to disable highlight.js

  label:
    text: "Omer Segev"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: true # needs to be explicitly set
    title: My documentation project
    subtitle: |
      For many years I have been working in the field of DevOps / Cloud / Infrastructure and I am dedicated to sharing my knowledge and experience with others through this blog. My goal is to provide valuable and informative content that will help our readers improve their skills and succeed in their DevOps and platforms endeavors.
    imageUrl: "tech.jpeg"
    imageWidth: 320
    imageHeight: 240
    imageTitle: Omer
    # buttons:
    #   - name: Documents
    #     url: docs
    #   - name: Cheatsheet
    #     url: cheatsheet
    #   - name: Search
    #     url: search

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/omersegev/"
    - name: github
      url: "https://github.com/omers"

  analytics:
    google:
      SiteVerificationTag: "G-21XGG2919L"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/omers/omers.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    codeFences: true
    lineNoStart: 1
    lineNos: false
menu:
    main:
        - identifier: documentation
          name: Documentation
          url: /Docs/
          weight: 10
        - identifier: cheatsheet
          name: Cheatsheets
          url: /cheatsheet/
          weight: 20
        - identifier: search
          name: Search
          url: /search/
          weight: 30
        - identifier: about
          name: About
          url: /about/
          weight: 40
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 50
          #parent: documentation
