baseURL: "https://omers.github.io/"
title: Omers Blog
paginate: 15
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-6790092-4
outputs:
    home:
        - HTML
        - RSS
        - JSON

minify:
  disableXML: false
  minifyOutput: true


params:
  env: production
  title: Omers Blog
  description: "ExampleSite description"
  keywords: [Blog, Portfolio]
  author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: false # to disable highlight.js

  label:
    text: "Omers Page"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: true # needs to be explicitly set
    title: Omers Page
    subtitle: "DevOps"
    imageUrl: "omer.jpeg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Omer
    buttons:
      - name: Docs
        url: docs
      - name: Search
        url: search
      - name: Cheatsheet
        url: cheatsheet

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com"
    - name: github
      url: "https://github.com/omers"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/omers/omers.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# menu:
#   main:
#     - identifier: docs
#       name: docs
#       url: /docs/
#       weight: 10
#     - identifier: cheatsheet
#       name: cheatsheet
#       url: /cheatsheet/
#       weight: 20
#     - identifier: search
#       name: search
#       url: /search/
#       weight: 30
#     - identifier: tags
#       name: tags
#       url: /tags/
#       weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    codeFences: true
    lineNoStart: 1
    lineNos: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai