baseURL: "https://omers.github.io/"
title: Omers Blog
paginate: 15
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-6790092-4
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

minify:
  disableXML: false
  minifyOutput: true


params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Omers Blog
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Omers Page"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Omers Page
    subtitle: "DevOps"
    imageUrl: "omer.jpeg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Omer
    buttons:
      - name: Docs
        url: docs
      - name: Search
        url: search
      - name: Cheatsheet
        url: cheatsheet

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: |
  #     Welcome to my Blog

  socialIcons:
    - name: linkedin
      url: "https://linkedin.com"
    - name: github
      url: "https://github.com/omers"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# menu:
#   main:
#     - identifier: docs
#       name: docs
#       url: /docs/
#       weight: 10
#     - identifier: cheatsheet
#       name: cheatsheet
#       url: /cheatsheet/
#       weight: 20
#     - identifier: search
#       name: search
#       url: /search/
#       weight: 30
#     - identifier: tags
#       name: tags
#       url: /tags/
#       weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    codeFences: true
    lineNoStart: 1
    lineNos: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai